### ISSUE TITLE
Ice caves shortcut% lost when using teleporter

### ISSUE THREAD

**Issue by Landiie** [spelunky-fyi/modlunky2#202]
If you use a teleporter on ice caves shortcut%, it looses it's prefix, completly voiding the existence of it being an ics run: 

(when there are no modifiers present, it will just display any% like any normal non ics run)

![demo](https://i.imgur.com/mEHFw01.gif)

P.S. when opening and closing the tracker when there is no modifiers present after teleporting, it can properly display Ice Caves Shortcut%

![alt demo](https://i.imgur.com/5WbYKaH.gif)

**Comment by mauvealerts** [comment]
This is intended, even though it isn't great... All "Ice Caves Shortcut%" categories require complying with Low%. The only reason it displays ICS% when you start the tracker _after_ teleporting is because we only invalidate Low% (and No TP) when you actually teleport.

Although this is arguably a general problem with shortcuts, I see how it's extra weird with ICS since the category name is related to (but not the same as) the starting point.

**Comment by gmjosack** [comment]
Not sure what to even show here. "No Valid Run" or something? :D

**Comment by mauvealerts** [comment]
Yeah, I've been hesitant to show "invalid" or similar because it's so
drastic and loses info. It's also really hard to implement in the current
design: `RunState` tracks individual criteria while `RunLabel` tracks the
combination of them.

What finally clicked with Landie's report is there are only a few reasons a
run is totally invalid:

* Death — Death% covers this well
* Starting after 1-1 — seems tractable?
* Mods — doesn't seem worthwhile

My current idea is to display starting level in parentheses, e.g. "(1-4) No
TP Any%". That seems easier to understand than my past ideas: "N/A" prefix,
adding an asterisk, etc.
