### ISSUE TITLE
Game not opening when I don't have speedrun mode on

### ISSUE THREAD

**Issue by TheNovelUWrknOn** [spelunky-fyi/modlunky2#291]
When I play spelunky 2 I can't open it without haveing speedrun mode on I tryed nighty stable uninstalling nothing is working

**Comment by mauvealerts** [comment]
Offhand, this might be due to a mod that gets disabled in speedrun mode? You could try manually disabling a mod, launching (w/o speedrun) and see if that finds one.

Otherwise, we'll need some information to work with. Are there any messages in the modlunky2 console? What mods do you have installed?

Also, `#s2-modding-help`  in the [community discord](https://discord.gg/spelunky-community) might be a good place to try discussing this. It's pretty active.

**Comment by TheNovelUWrknOn** [comment]
I found out what the problem was. Thanks for the help!
