### ISSUE TITLE
What is .fnb file in the Fonts folder and how to edit it?

### ISSUE THREAD

**Issue by OTOMariK** [spelunky-fyi/modlunky2#38]
I would like to make a mod that can convert the text to other language, it seems that I should replace these font files in the Fonts folder to support the new language. How can I achieve this?

**Comment by gmjosack** [comment]
I'm not familiar with fnb extensions unfortunately. I'm going to close this issue because it's not related to modlunky2 specifically. I'f recommend either leaving a comment on https://spelunky.fyi/mods/m/korean-patch-mod/ asking for information on how they did it or reaching out to the modding community in the #s2-modding channel over at http://discord.gg/spelunky-community
